libpdbg: Remove unused __unused from compiler.h
The compiler.h header contains a macro that defines __unused. When
building against uClibc this collides with uClibc_stdio.h:

In file included from /usr/include/stdio.h:71:0,
                 from libpdbg/fake.c:17:
/usr/include/bits/uClibc_stdio.h:149:16: error: expected identifier or ‘(’ before ‘;’ token
  void *__unused;    /* Placeholder for codeset binding. */
                ^

As it is unused in pdbg, remove it.

Signed-off-by: Joel Stanley <joel@jms.id.au>